apiVersion: v1
kind: ConfigMap
metadata:
  name: clouddevopsproject-config
  namespace: ivolve
data:
  APP_ENV: "development"
  APP_DEBUG: "true"
  APP_LOG_LEVEL: "info"
  DATABASE_HOST: "mydb.example.com"
  DATABASE_PORT: "5432"

