apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddevopsproject-deployment
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clouddevopsproject
  template:
    metadata:
      labels:
        app: clouddevopsproject
    spec:
      containers:
        - name: clouddevopsproject
          image: abdelrhmanehab11/test:latest
          ports:
            - containerPort: 5000   # نفس الـ port اللي التطبيق شغال عليه
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: clouddevopsproject-secret
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clouddevopsproject-secret
                  key: DATABASE_PASSWORD
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: clouddevopsproject-secret
                  key: API_KEY
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: clouddevopsproject-dockerhub-secret

