apiVersion: v1
kind: Secret
metadata:
  name: clouddevopsproject-secret
  namespace: ivolve
type: Opaque
data:
  DATABASE_USER: YWRtaW4=          
  DATABASE_PASSWORD: cGFzc3dvcmQ= 
  API_KEY: MTIzNDU2Nzg5MA==        
