apiVersion: v1
kind: Service
metadata:
  name: clouddevopsproject-service
  namespace: ivolve
spec:
  selector:
    app: clouddevopsproject
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer

