apiVersion: v1
kind: Service
metadata:
  name: clouddevopsproject-nodeport
  namespace: ivolve
  labels:
    app: clouddevopsproject
spec:
  type: NodePort
  selector:
    app: clouddevopsproject
  ports:
  - name: http
    port: 80      
    targetPort: 80    
    nodePort: 30036                             
    protocol: TCP

